import type { NextPage } from 'next'
import Head from 'next/head'
import Dynamic from 'next/dynamic'

const Map = Dynamic(() => import('../modules/game/components/Map'), { ssr: false })

const Game: NextPage = () => {
    return (
        <>
            <Head>
                <title>Game • Space Explorers</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Map />
        </>
    )
}

export default Game
