import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Map from '../modules/game/components/Map'

const Game: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Game • Space Explorers</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Map />
        </div>
    )
}

export default Game
